"""empty message

Revision ID: b62060230d9e
Revises: 
Create Date: 2020-01-30 00:11:56.516590

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b62060230d9e'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crash',
    sa.Column('aboard', sa.Integer(), nullable=True),
    sa.Column('fatalities', sa.Integer(), nullable=True),
    sa.Column('ground', sa.Integer(), nullable=True),
    sa.Column('datetime', sa.DateTime(), nullable=False),
    sa.Column('location', sa.String(length=128), nullable=True),
    sa.Column('summary', sa.String(length=1000), nullable=True),
    sa.PrimaryKeyConstraint('datetime')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('crash')
    # ### end Alembic commands ###
